# Name of the program or library

NAME = libftprintf

# Flags and Compilers

CC = cc
CFLAGS = -Wall -Werror -Wextra

# Directories

SRCDIR = .
INCDIR = .

# SRCS

SRCS =	$(SRCDIR)/ft_printf.c\
	$(SRCDIR)/convert_hex_to_str.c\
	$(SRCDIR)/print_char.c\
	$(SRCDIR)/convert_int_to_str.c\
	$(SRCDIR)/handle_specifier.c
	$(SRCDIR)/convert_ptr_to_str.c\
	$(SRCDIR)/print_percentage.c\
	$(SRCDIR)/print_str.c\
	$(SRCDIR)/parse_format.c\
	$(SRCDIR)/convert_unsigned_to_str.c

# OBJS

OBJS = $(SRCS:.c=.o)

# Main

all: $(NAME)

# Main rule

$(NAME): 
