#!/bin/bash

MINISHELL_PATH="../minishell"

# Run a specific test if the file name was specified
if [[ $1 ]]; then
    test_lists=(
        $1
    )
else
    test_lists=(
        "builtins"
        "pipes"
        "redirects"
        "extras"
        "minipip"
        "bool"
        "errors"
    )
fi

if [[ $1 == "wildcards"  || $1 == "bonus" ]]; then
    MINISHELL_PATH="../minishell_bonus"
fi

BOLD="\e[1m"
YELLOW="\033[0;33m"
GREY="\033[38;5;244m"
PURPLE="\033[0;35m"
BLUE="\033[0;36m"
RED="\e[0;31m"
END="\033[0m"

chmod 000 ./test_files/invalid_permission
mkdir ./outfiles
mkdir ./mini_outfiles
mkdir ./bash_outfiles

printf $RED
echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥";
echo "                                                                                             ";
echo " ██    ██ █ ██    █ █ █████ █   █ █████ █     █       ██████ █████ █████ ██████ █████ █████  ";
echo " ███  ███ █ ███   █ █ █     █   █ █     █     █         ██   █     █       ██   █     █   ██ ";
echo " █ ████ █ █ █ ██  █ █ █████ █████ ████  █     █         ██   ████  █████   ██   ████  █████  ";
echo " █  ██  █ █ █  ██ █ █     █ █   █ █     █     █         ██   █         █   ██   █     █   ██ ";
echo " █      █ █ █   ███ █ █████ █   █ █████ █████ █████     ██   █████ █████   ██   █████ █   ██ ";
echo "                                                                                             ";
echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥";
echo "                                                                                              ";

PROMPT=$(echo -e "\nexit\n" | $MINISHELL_PATH | head -n 1 | sed "s/\x1B\[[0-9;]\{1,\}[A-Za-z]//g" )
# Helper commands:
REMOVE_COLORS="sed s/\x1B\[[0-9;]\{1,\}[A-Za-z]//g"
REMOVE_EXIT="grep -v ^exit$"

for testfile in ${test_lists[*]}; do

    printf $RED
    echo ———————————— $testfile

    while read teste; do
        ((i++))

        rm -rf ./outfiles/*
        rm -rf ./mini_outfiles/*
        MINI_OUTPUT=$(echo -e "$teste" | $MINISHELL_PATH 2> /dev/null | $REMOVE_COLORS | grep -vF "$PROMPT" | $REMOVE_EXIT )
        MINI_OUTFILES=$(cp ./outfiles/* ./mini_outfiles &>/dev/null)

        # Run Valgrind
        VALGRIND_LOG="valgrind.log"
        valgrind --leak-check=full --show-leak-kinds=all --trace-children=yes --track-origins=yes --suppressions=lib.supp --log-file=$VALGRIND_LOG $MINISHELL_PATH <<< "$teste" > /dev/null 2>&1
        
        VALGRIND_ERRORS=$(grep -E "definitely lost|indirectly lost|still reachable|invalid read|invalid write|double free" $VALGRIND_LOG)

        printf $YELLOW
        printf "Test %3s: " $i
        if [ -z "$VALGRIND_ERRORS" ]; then
            printf "ok"
            ((ok++))
        else
            printf "❌"
            echo "Valgrind errors detected:"
            cat $VALGRIND_LOG
        fi
        printf "$GREY $teste \n$END"
    done < $testfile
done

chmod 666 ./test_files/invalid_permission
rm -rf ./outfiles
rm -rf ./mini_outfiles
rm -rf ./bash_outfiles

printf $PURPLE
printf $BOLD
echo   $ok/$i
printf $END

if [[ "$ok" == "$i" ]]; then
    echo "🎊 🎊 🎊"
    echo "😎 😎 😎"
    echo "🎉 🎉 🎉"
    exit 0
else
    echo "😭 😭 😭"
    exit 1
fi

